//Json object with employees details
var oEmployeeInfo = {
    "employees": [{
        "lastName": "Pullur",
        "empid": "44",
        "workloc": "Hyderabad",
        "email": "jay.pullur@abc.com",
        "status": "1",
        "fullName": "Jay Pullur",
        "firstName": "Jay",
        "telephone": "44",
        "seatloc": "5FC SUITE",
        "mobile": "91 (984) 4534-2939"
    }, {
        "lastName": "Prasanna Pullur",
        "empid": "10004",
        "workloc": "Mountain View, CA",
        "email": "vijay@xyz.com",
        "status": "1",
        "fullName": "Vijay Prasanna Pullur",
        "firstName": "Vijay",
        "telephone": "4543",
        "seatloc": "",
        "mobile": "1 (408) 454-1916"
    }, {
        "lastName": "Barua",
        "empid": "54667",
        "workloc": "Hyderabad",
        "email": "hrish@fdj.com",
        "status": "1",
        "fullName": "Hrishikesh Barua",
        "firstName": "Hrishikesh",
        "telephone": "433",
        "seatloc": "5F154",
        "mobile": "91 (984) 942-2334"
    },{
        "lastName": "Mahapatra",
        "empid": "56565",
        "workloc": "Hyderabad",
        "email": "sibaprasad.mahapatra@ergf.com",
        "status": "1",
        "fullName": "Sibaprasad Mahapatra",
        "firstName": "Sibaprasad",
        "telephone": "NULL",
        "seatloc": "2F118",
        "mobile": "(991) 665-5655"
    }, {
        "lastName": "Indi",
        "empid": "34543",
        "workloc": "Bengaluru",
        "email": "shruthi.indi@amkc.com",
        "status": "1",
        "fullName": "Shruthi Indi",
        "firstName": "Shruthi",
        "telephone": "NULL",
        "seatloc": "NULL",
        "mobile": "(968) 653-7833"
    }, {
        "lastName": "Indukuri",
        "empid": "32424",
        "workloc": "hyderabad",
        "email": "sandeep.indukuri@ahha.com",
        "status": "1",
        "fullName": "Sandeep Varma Indukuri",
        "firstName": "Sandeep Varma",
        "telephone": "NULL",
        "seatloc": "XXXXX",
        "mobile": "7785484893"
    }, {
        "lastName": "Yadav",
        "empid": "12345",
        "workloc": "Hyderabad",
        "email": "dinesh.yadav@hskka.com",
        "status": "1",
        "fullName": "Dinesh Yadav",
        "firstName": "Dinesh",
        "telephone": "NULL",
        "seatloc": "4F095",
        "mobile": "(982) 834-3565"
    }, {
        "lastName": "Vallabhajosyula",
        "empid": "433235",
        "workloc": "Hyderabad",
        "email": "aditya.vallabhajosyula@nfdkkk.com",
        "status": "1",
        "fullName": "Aditya Vallabhajosyula",
        "firstName": "Aditya",
        "telephone": "NULL",
        "seatloc": "5F146",
        "mobile": "(897) 748-7484"
    }, {
        "lastName": "Murari",
        "empid": "12335",
        "workloc": "Hyderabad",
        "email": "kiran.murari@hjdfjk.com",
        "status": "1",
        "fullName": "Kiran Murari",
        "firstName": "Kiran",
        "telephone": "NULL",
        "seatloc": "4F122",
        "mobile": "(910) 068-76534"
    }, {
        "lastName": "Jaladi",
        "empid": "3422",
        "workloc": "Hyderabad",
        "email": "sivakishore.jaladi@hdh.com",
        "status": "1",
        "fullName": "Veera Venkata Siva Kishore Jaladi",
        "firstName": "Veera Venkata Siva Kishore",
        "telephone": "NULL",
        "seatloc": "2F144",
        "mobile": "(986) 637-4543"
    }, {
        "lastName": "Y",
        "empid": "1896133",
        "workloc": "Bengaluru",
        "email": "ananth.kumar@imfgf.com",
        "status": "1",
        "fullName": "Ananth Kumar Y",
        "firstName": "Ananth Kumar",
        "telephone": "NULL",
        "seatloc": "NULL",
        "mobile": "(973) 868-6613"
    }, {
        "lastName": "Vakiti",
        "empid": "456987",
        "workloc": "Hyderabad",
        "email": "bandhavya.vakiti@dhhmi.com",
        "status": "1",
        "fullName": "Bandhavya Vakiti",
        "firstName": "Bandhavya",
        "telephone": "NULL",
        "seatloc": "4F087",
        "mobile": "(720) 755-2563"
    }, {
        "lastName": "Dhawan",
        "empid": "12135",
        "workloc": "Hyderabad",
        "email": "aditya.dhawan@cfjhb.com",
        "status": "1",
        "fullName": "Aditya Dhawan",
        "firstName": "Aditya",
        "telephone": "NULL",
        "seatloc": "3F038",
        "mobile": "(768) 093-05563"
    }, {
        "lastName": "Singh",
        "empid": "12136",
        "workloc": "Hyderabad",
        "email": "vishal.singh@drgy.com",
        "status": "1",
        "fullName": "Vishal Singh",
        "firstName": "Vishal",
        "telephone": "NULL",
        "seatloc": "4F143",
        "mobile": "(789) 385-6738"
    }, {
        "lastName": "Singh",
        "empid": "12137",
        "workloc": "Hyderabad",
        "email": "medha.singh@fdkjfkd.com",
        "status": "1",
        "fullName": "Medha Singh",
        "firstName": "Medha",
        "telephone": "NULL",
        "seatloc": "NULL",
        "mobile": "(988) 513-12343"
    }, {
        "lastName": "Chavan",
        "empid": "12138",
        "workloc": "Bengaluru",
        "email": "vasudev.chavan@fhdhb.com",
        "status": "1",
        "fullName": "Vasudev Chavan",
        "firstName": "Vasudev",
        "telephone": "NULL",
        "seatloc": "NULL",
        "mobile": "(974) 001-34312"
    }, {
        "lastName": "Periasamy",
        "empid": "12139",
        "workloc": "Chennai",
        "email": "oormila.periasamy@vcxx.com",
        "status": "1",
        "fullName": "Oormila Periasamy",
        "firstName": "Oormila",
        "telephone": "NULL",
        "seatloc": "NULL",
        "mobile": "(967) 786-87009"
    }, {
        "lastName": "Vijai",
        "empid": "12140",
        "workloc": "Chennai",
        "email": "neha.vijai@iooiu.com",
        "status": "1",
        "fullName": "Neha Vijai",
        "firstName": "Neha",
        "telephone": "NULL",
        "seatloc": "NULL",
        "mobile": "(770) 862-89877"
    }, {
        "lastName": "P",
        "empid": "12141",
        "workloc": "Chennai",
        "email": "mahendran.p@ljmp.com",
        "status": "1",
        "fullName": "Mahendran P",
        "firstName": "Mahendran",
        "telephone": "NULL",
        "seatloc": "NULL",
        "mobile": "(979) 089-7645"
    }, {
        "lastName": "Jain",
        "empid": "12142",
        "workloc": "Hyderabad",
        "email": "shikha.jain@fsdh.com",
        "status": "1",
        "fullName": "Shikha Jain",
        "firstName": "Shikha",
        "telephone": "NULL",
        "seatloc": "4F090",
        "mobile": "78467956053"
    }, {
        "lastName": "Sinha",
        "empid": "12152",
        "workloc": "Chennai",
        "email": "sweta.sinha@vcbn.com",
        "status": "1",
        "fullName": "Sweta Sinha",
        "firstName": "Sweta",
        "telephone": "NULL",
        "seatloc": "NULL",
        "mobile": "(902) 457-0987"
    }, {
        "lastName": "Thotakura",
        "empid": "12151",
        "workloc": "Chennai",
        "email": "satyadileep.t@tyuj.com",
        "status": "1",
        "fullName": "Satya Dileep Thotakura",
        "firstName": "Satya Dileep",
        "telephone": "NULL",
        "seatloc": "NULL",
        "mobile": "(978) 999-8785"
    }]
}